# Change these first
owner: ForgottenWorld # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Forum
    method: HEAD
    url: https://forum.forgottenworld.it
  - name: Wiki
    method: HEAD
    url: https://wiki.forgottenworld.it
  - name: MC server api
    url: https://fwapi.forgottenworld.it
  - name: Home
    method: HEAD
    url: https://home.forgottenworld.it

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ForgottenWorld
  navbar:
    - title: Status
      href: /upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://home.forgottenworld.it/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
